import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { FlexLayoutModule } from '@angular/flex-layout';
import {
    MatSlideToggleModule,
    MatAutocompleteModule,
    MatProgressSpinnerModule,
    MatButtonModule,
    MatToolbarModule,
    MatIconModule,
    MatCardModule,
    MatInputModule,
    MatButtonToggleModule,
    MatListModule,
    MatGridListModule,
    MatMenuModule,
    MatSidenavModule,
    MatProgressBarModule,
    MatTabsModule,
    MatSelectModule,
    MatRadioModule,
    MatDatepickerModule,
    MatOptionModule,
    MatSnackBarModule,
    MatNativeDateModule,
    MatFormFieldModule,
    MatCheckboxModule,
    MatExpansionModule,
    MatStepperModule,
    MatDialogModule,
    MatChipsModule,
    MatTableModule,
    MatTooltipModule,
    MatPaginatorModule,
    MatBadgeModule
} from '@angular/material';


export const Mat_LOADERS = {
    IMPORTS: [
        FlexLayoutModule,
        MatSlideToggleModule,
        MatAutocompleteModule,
        MatProgressSpinnerModule,
        MatButtonModule,
        MatToolbarModule,
        MatIconModule,
        MatCardModule,
        MatInputModule,
        MatButtonToggleModule,
        MatListModule,
        MatGridListModule,
        MatMenuModule,
        MatSidenavModule,
        MatProgressBarModule,
        MatTabsModule,
        MatSelectModule,
        MatRadioModule,
        MatDatepickerModule,
        MatOptionModule,
        MatSnackBarModule,
        MatNativeDateModule,
        MatFormFieldModule,
        MatCheckboxModule,
        MatExpansionModule,
        MatStepperModule,
        MatDialogModule,
        MatChipsModule,
        MatTableModule,
        MatTooltipModule,
        MatPaginatorModule,
        MatBadgeModule
    ]
};
